### ISSUE TITLE
info.vue页面 发帖人予评论人名称不一

### ISSUE THREAD

**Issue by MapleNe** [buxia97/RuleApp#2]
发帖者设置昵称为A发帖时显示为A 但是在该评论区下方显示为用户名
![image](https://user-images.githubusercontent.com/43572630/212625684-5425271e-92fc-4267-9a05-d9a91d109d72.png)

**Comment by buxia97** [comment]
这是由API引起的问题，会在API的最新内测版修复

**Comment by buxia97** [comment]
已在API最新内测版完成修复。
